Search.appendIndex(
    [
                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance",
            "name": "Balance",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_getAmount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_getCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003A\u0024amount",
            "name": "amount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#property_amount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Balance\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Balance.html#property_currency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close",
            "name": "Close",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Close\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Close.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity",
            "name": "Commodity",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method_getCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method_getMetadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#property_currency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Commodity\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Commodity.html#property_metadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom",
            "name": "Custom",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method_getName"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method_getValues"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#property_name"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Custom\u003A\u003A\u0024values",
            "name": "values",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Custom.html#property_values"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\DirectiveInterface",
            "name": "DirectiveInterface",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-DirectiveInterface.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\DirectiveInterface\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-DirectiveInterface.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\DirectiveInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-DirectiveInterface.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document",
            "name": "Document",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method_getPath"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Document\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Document.html#property_path"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event",
            "name": "Event",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method_getType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method_getDescription"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#property_type"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Event\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Event.html#property_description"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note",
            "name": "Note",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method_getMessage"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Note\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Note.html#property_message"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open",
            "name": "Open",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AgetCurrencies\u0028\u0029",
            "name": "getCurrencies",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_getCurrencies"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AgetBookingMethod\u0028\u0029",
            "name": "getBookingMethod",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_getBookingMethod"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003A\u0024currencies",
            "name": "currencies",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#property_currencies"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Open\u003A\u003A\u0024bookingMethod",
            "name": "bookingMethod",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Open.html#property_bookingMethod"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad",
            "name": "Pad",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetSourceAccount\u0028\u0029",
            "name": "getSourceAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getSourceAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getAmount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A\u0024sourceAccount",
            "name": "sourceAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#property_sourceAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A\u0024amount",
            "name": "amount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#property_amount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Pad\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Pad.html#property_currency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting",
            "name": "Posting",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getAmount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetCost\u0028\u0029",
            "name": "getCost",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getCost"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetCostCurrency\u0028\u0029",
            "name": "getCostCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getCostCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetPrice\u0028\u0029",
            "name": "getPrice",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getPrice"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetPriceCurrency\u0028\u0029",
            "name": "getPriceCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getPriceCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetPriceType\u0028\u0029",
            "name": "getPriceType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getPriceType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getMetadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_account"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024amount",
            "name": "amount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_amount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_currency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024cost",
            "name": "cost",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_cost"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024costCurrency",
            "name": "costCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_costCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024price",
            "name": "price",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_price"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024priceCurrency",
            "name": "priceCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_priceCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024priceType",
            "name": "priceType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_priceType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Posting\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Posting.html#property_metadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price",
            "name": "Price",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_getCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_getAmount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AgetPriceCurrency\u0028\u0029",
            "name": "getPriceCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_getPriceCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#property_currency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003A\u0024amount",
            "name": "amount",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#property_amount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Price\u003A\u003A\u0024priceCurrency",
            "name": "priceCurrency",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Price.html#property_priceCurrency"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query",
            "name": "Query",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method_getName"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003AgetQueryString\u0028\u0029",
            "name": "getQueryString",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method_getQueryString"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#property_name"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Query\u003A\u003A\u0024queryString",
            "name": "queryString",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Query.html#property_queryString"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction",
            "name": "Transaction",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getDate"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetFlag\u0028\u0029",
            "name": "getFlag",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getFlag"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetPayee\u0028\u0029",
            "name": "getPayee",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getPayee"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetNarration\u0028\u0029",
            "name": "getNarration",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getNarration"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getTags"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetLinks\u0028\u0029",
            "name": "getLinks",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getLinks"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetPostings\u0028\u0029",
            "name": "getPostings",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getPostings"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getMetadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AgetDirectiveType\u0028\u0029",
            "name": "getDirectiveType",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_getDirectiveType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#method_toArray"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024date",
            "name": "date",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_date"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024flag",
            "name": "flag",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_flag"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024payee",
            "name": "payee",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_payee"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024narration",
            "name": "narration",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_narration"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_tags"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024links",
            "name": "links",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_links"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024postings",
            "name": "postings",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_postings"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive\\Transaction\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Directive-Transaction.html#property_metadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException",
            "name": "ParseException",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException\u003A\u003AgetErrorLine\u0028\u0029",
            "name": "getErrorLine",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html#method_getErrorLine"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException\u003A\u003AgetErrorColumn\u0028\u0029",
            "name": "getErrorColumn",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html#method_getErrorColumn"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException\u003A\u003A\u0024errorLine",
            "name": "errorLine",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html#property_errorLine"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception\\ParseException\u003A\u003A\u0024errorColumn",
            "name": "errorColumn",
            "summary": "",
            "url": "classes/Beancount-Parser-Exception-ParseException.html#property_errorColumn"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser",
            "name": "Parser",
            "summary": "Main\u0020parser\u0020for\u0020Beancount\u0020double\u002Dentry\u0020bookkeeping\u0020files.",
            "url": "classes/Beancount-Parser-Parser.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020Parser\u0020instance.",
            "url": "classes/Beancount-Parser-Parser.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020the\u0020Beancount\u0020content\u0020and\u0020returns\u0020an\u0020array\u0020of\u0020directives.",
            "url": "classes/Beancount-Parser-Parser.html#method_parse"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseDirective\u0028\u0029",
            "name": "parseDirective",
            "summary": "Parses\u0020a\u0020single\u0020directive\u0020from\u0020the\u0020current\u0020position.",
            "url": "classes/Beancount-Parser-Parser.html#method_parseDirective"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseDatedDirective\u0028\u0029",
            "name": "parseDatedDirective",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseDatedDirective"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseOpen\u0028\u0029",
            "name": "parseOpen",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseOpen"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseClose\u0028\u0029",
            "name": "parseClose",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseClose"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseBalance\u0028\u0029",
            "name": "parseBalance",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseBalance"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseCommodity\u0028\u0029",
            "name": "parseCommodity",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseCommodity"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparsePad\u0028\u0029",
            "name": "parsePad",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parsePad"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseNote\u0028\u0029",
            "name": "parseNote",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseNote"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseDocument\u0028\u0029",
            "name": "parseDocument",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseDocument"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparsePrice\u0028\u0029",
            "name": "parsePrice",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parsePrice"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseEvent\u0028\u0029",
            "name": "parseEvent",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseEvent"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseQuery\u0028\u0029",
            "name": "parseQuery",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseQuery"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseCustom\u0028\u0029",
            "name": "parseCustom",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseCustom"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseTransaction\u0028\u0029",
            "name": "parseTransaction",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseTransaction"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparsePosting\u0028\u0029",
            "name": "parsePosting",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parsePosting"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseCostOrPriceParts\u0028\u0029",
            "name": "parseCostOrPriceParts",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseCostOrPriceParts"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparsePriceAmount\u0028\u0029",
            "name": "parsePriceAmount",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parsePriceAmount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseMetadata\u0028\u0029",
            "name": "parseMetadata",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseMetadata"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AexpectAccount\u0028\u0029",
            "name": "expectAccount",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_expectAccount"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AparseAccountName\u0028\u0029",
            "name": "parseAccountName",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_parseAccountName"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003Aexpect\u0028\u0029",
            "name": "expect",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_expect"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_peek"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003Aadvance\u0028\u0029",
            "name": "advance",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_advance"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AisAtEnd\u0028\u0029",
            "name": "isAtEnd",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_isAtEnd"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AisNextTokenEOL\u0028\u0029",
            "name": "isNextTokenEOL",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_isNextTokenEOL"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003AskipEOL\u0028\u0029",
            "name": "skipEOL",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_skipEOL"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003ApeekLine\u0028\u0029",
            "name": "peekLine",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_peekLine"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003ApeekColumn\u0028\u0029",
            "name": "peekColumn",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#method_peekColumn"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003A\u0024tokens",
            "name": "tokens",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#property_tokens"
        },                {
            "fqsen": "\\Beancount\\Parser\\Parser\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/Beancount-Parser-Parser.html#property_position"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token",
            "name": "Token",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method_getType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method_getValue"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003AgetLine\u0028\u0029",
            "name": "getLine",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method_getLine"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003AgetColumn\u0028\u0029",
            "name": "getColumn",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method_getColumn"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#method___toString"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#property_type"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#property_value"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A\u0024line",
            "name": "line",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#property_line"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\Token\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-Token.html#property_column"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface",
            "name": "TokenInterface",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#method_getType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#method_getValue"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AgetLine\u0028\u0029",
            "name": "getLine",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#method_getLine"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AgetColumn\u0028\u0029",
            "name": "getColumn",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#method_getColumn"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ADATE",
            "name": "DATE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_DATE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AFLAG",
            "name": "FLAG",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_FLAG"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ASTRING",
            "name": "STRING",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_STRING"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ANUMBER",
            "name": "NUMBER",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_NUMBER"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AIDENTIFIER",
            "name": "IDENTIFIER",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_IDENTIFIER"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AACCOUNT",
            "name": "ACCOUNT",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_ACCOUNT"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACURRENCY",
            "name": "CURRENCY",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_CURRENCY"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ASYMBOL",
            "name": "SYMBOL",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_SYMBOL"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AOPEN",
            "name": "OPEN",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_OPEN"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACLOSE",
            "name": "CLOSE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_CLOSE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ABALANCE",
            "name": "BALANCE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_BALANCE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003APAD",
            "name": "PAD",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_PAD"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ANOTE",
            "name": "NOTE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_NOTE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ADOCUMENT",
            "name": "DOCUMENT",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_DOCUMENT"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACOMMODITY",
            "name": "COMMODITY",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_COMMODITY"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003APRICE",
            "name": "PRICE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_PRICE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AEVENT",
            "name": "EVENT",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_EVENT"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AQUERY",
            "name": "QUERY",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_QUERY"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACUSTOM",
            "name": "CUSTOM",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_CUSTOM"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ATXN",
            "name": "TXN",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_TXN"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AEOF",
            "name": "EOF",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_EOF"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AEOL",
            "name": "EOL",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_EOL"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACOST",
            "name": "COST",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_COST"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003APRICE_AT",
            "name": "PRICE_AT",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_PRICE_AT"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ATOTAL_PRICE",
            "name": "TOTAL_PRICE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_TOTAL_PRICE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ATAG",
            "name": "TAG",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_TAG"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ALINK",
            "name": "LINK",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_LINK"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AKEY",
            "name": "KEY",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_KEY"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003AWHITESPACE",
            "name": "WHITESPACE",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_WHITESPACE"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token\\TokenInterface\u003A\u003ACOMMENT",
            "name": "COMMENT",
            "summary": "",
            "url": "classes/Beancount-Parser-Token-TokenInterface.html#constant_COMMENT"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer",
            "name": "Tokenizer",
            "summary": "Tokenizer\u0020\u0028Lexer\u0029\u0020for\u0020Beancount\u0020files.",
            "url": "classes/Beancount-Parser-Tokenizer.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020Tokenizer\u0020instance.",
            "url": "classes/Beancount-Parser-Tokenizer.html#method___construct"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003Atokenize\u0028\u0029",
            "name": "tokenize",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_tokenize"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_reset"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanToken\u0028\u0029",
            "name": "scanToken",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanToken"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AisAtCommentStart\u0028\u0029",
            "name": "isAtCommentStart",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_isAtCommentStart"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanComment\u0028\u0029",
            "name": "scanComment",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanComment"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanString\u0028\u0029",
            "name": "scanString",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanString"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanCost\u0028\u0029",
            "name": "scanCost",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanCost"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanPrice\u0028\u0029",
            "name": "scanPrice",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanPrice"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanTag\u0028\u0029",
            "name": "scanTag",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanTag"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanLink\u0028\u0029",
            "name": "scanLink",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanLink"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanDateOrNumber\u0028\u0029",
            "name": "scanDateOrNumber",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanDateOrNumber"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanNumber\u0028\u0029",
            "name": "scanNumber",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanNumber"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AscanIdentifier\u0028\u0029",
            "name": "scanIdentifier",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_scanIdentifier"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AisAccountType\u0028\u0029",
            "name": "isAccountType",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_isAccountType"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AisValidCurrencyCode\u0028\u0029",
            "name": "isValidCurrencyCode",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_isValidCurrencyCode"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AisWhitespaceOrEOL\u0028\u0029",
            "name": "isWhitespaceOrEOL",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_isWhitespaceOrEOL"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_peek"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003Aadvance\u0028\u0029",
            "name": "advance",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_advance"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AisAtEnd\u0028\u0029",
            "name": "isAtEnd",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#method_isAtEnd"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003ADIRECTIVE_KEYWORDS",
            "name": "DIRECTIVE_KEYWORDS",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#constant_DIRECTIVE_KEYWORDS"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003AVALID_ACCOUNT_TYPES",
            "name": "VALID_ACCOUNT_TYPES",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#constant_VALID_ACCOUNT_TYPES"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#property_input"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#property_position"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003A\u0024line",
            "name": "line",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#property_line"
        },                {
            "fqsen": "\\Beancount\\Parser\\Tokenizer\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Beancount-Parser-Tokenizer.html#property_column"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Directive",
            "name": "Directive",
            "summary": "",
            "url": "namespaces/beancount-parser-directive.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/beancount-parser-exception.html"
        },                {
            "fqsen": "\\Beancount\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/beancount-parser.html"
        },                {
            "fqsen": "\\Beancount",
            "name": "Beancount",
            "summary": "",
            "url": "namespaces/beancount.html"
        },                {
            "fqsen": "\\Beancount\\Parser\\Token",
            "name": "Token",
            "summary": "",
            "url": "namespaces/beancount-parser-token.html"
        }            ]
);
